export const themes = [
    { name: "Create +" },
    { name: "3024 Night" },
    { name: "A11y Dark" },
    { name: "Blackboard" },
    { name: "Base 16 (Dark)" },
    { name: "Base 16 (Light)" },
    { name: "Cobalt" },
    { name: "Dracula Pro", note: "Purchase" },
    { name: "Duotone" },
    { name: "Hopscotch" },
    { name: "Lucario" },
    { name: "Material" },
    { name: "Monokai" },
    { name: "Night Owl" },
    { name: "Nord" },
    { name: "Oceanic Next" },
    { name: "One Light" },
    { name: "One Dark" },
    { name: "Panda" },
    { name: "Paraiso" },
    { name: "Seti" },
    { name: "Shades of Purple" },
    { name: "Solarized (Dark)" },
    { name: "Solarized (Light)" },
    { name: "SynthWave '84" },
    { name: "Twilight" },
    { name: "Verminal" }
];